// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskGenie.Infrastructure.Persistence;

#nullable disable

namespace TaskGenie.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskGenie.Domain.Entities.ActivityLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("log_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("action");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("entity_type");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("LogId")
                        .HasName("PK__activity__9E2397E0EE5103A4");

                    b.ToTable("activity_logs", (string)null);
                });

            modelBuilder.Entity("TaskGenie.Domain.Entities.AiAnalysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnalysisType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("analysis_type");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("TaskId")
                        .HasColumnType("int")
                        .HasColumnName("task_id");

                    b.HasKey("Id")
                        .HasName("PK__ai_analy__3214EC0789A501F9");

                    b.HasIndex("TaskId");

                    b.ToTable("ai_analysis", (string)null);
                });

            modelBuilder.Entity("TaskGenie.Domain.Entities.AiRecommendation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("reason");

                    b.Property<string>("RecommendationType")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("assign")
                        .HasColumnName("recommendation_type");

                    b.Property<double?>("Score")
                        .HasColumnType("float")
                        .HasColumnName("score");

                    b.Property<int?>("SuggestedUserId")
                        .HasColumnType("int")
                        .HasColumnName("suggested_user_id");

                    b.Property<int?>("TaskId")
                        .HasColumnType("int")
                        .HasColumnName("task_id");

                    b.HasKey("Id")
                        .HasName("PK__ai_recom__3213E83FF227C486");

                    b.HasIndex("SuggestedUserId");

                    b.HasIndex("TaskId");

                    b.ToTable("ai_recommendations", (string)null);
                });

            modelBuilder.Entity("TaskGenie.Domain.Entities.Evaluation", b =>
                {
                    b.Property<int>("EvaluationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("evaluation_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EvaluationId"));

                    b.Property<int?>("CommunicationScore")
                        .HasColumnType("int")
                        .HasColumnName("communication_score");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("DeadlineScore")
                        .HasColumnType("int")
                        .HasColumnName("deadline_score");

                    b.Property<int?>("LeaderId")
                        .HasColumnType("int")
                        .HasColumnName("leader_id");

                    b.Property<int?>("SkillScore")
                        .HasColumnType("int")
                        .HasColumnName("skill_score");

                    b.Property<int?>("TeamworkScore")
                        .HasColumnType("int")
                        .HasColumnName("teamwork_score");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("EvaluationId")
                        .HasName("PK__evaluati__827C592DBCF1FB91");

                    b.HasIndex("LeaderId");

                    b.HasIndex("UserId");

                    b.ToTable("evaluations", (string)null);
                });

            modelBuilder.Entity("TaskGenie.Domain.Entities.Invitation", b =>
                {
                    b.Property<int>("InvitationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("invitation_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvitationId"));

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int")
                        .HasColumnName("team_id");

                    b.HasKey("InvitationId")
                        .HasName("PK__invitati__94B74D7C938D73DA");

                    b.HasIndex("TeamId");

                    b.ToTable("invitations", (string)null);
                });

            modelBuilder.Entity("TaskGenie.Domain.Entities.Meeting", b =>
                {
                    b.Property<int>("MeetingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("meeting_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MeetingId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndAt")
                        .HasColumnType("datetime")
                        .HasColumnName("end_at");

                    b.Property<string>("Location")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("location");

                    b.Property<int>("OrganizedBy")
                        .HasColumnType("int")
                        .HasColumnName("organized_by");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("project_id");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("datetime")
                        .HasColumnName("scheduled_at");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Scheduled")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("MeetingId")
                        .HasName("PK_meetings");

                    b.HasIndex("OrganizedBy");

                    b.HasIndex("ProjectId");

                    b.ToTable("meetings", (string)null);
                });

            modelBuilder.Entity("TaskGenie.Domain.Entities.MeetingAttendee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MeetingId")
                        .HasColumnType("int")
                        .HasColumnName("meeting_id");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Invited")
                        .HasColumnName("status");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK_meeting_attendees");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "MeetingId", "UserId" }, "UQ_meeting_attendees")
                        .IsUnique();

                    b.ToTable("meeting_attendees", (string)null);
                });

            modelBuilder.Entity("TaskGenie.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("notification_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("message");

                    b.Property<int?>("ReferenceId")
                        .HasColumnType("int")
                        .HasColumnName("reference_id");

                    b.Property<string>("ReferenceType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("reference_type");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("type");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("NotificationId")
                        .HasName("PK_notifications");

                    b.HasIndex("UserId");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("TaskGenie.Domain.Entities.Organization", b =>
                {
                    b.Property<int>("OrganizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrganizationId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Logo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("logo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("owner_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("OrganizationId")
                        .HasName("PK_organizations");

                    b.HasIndex("OwnerId");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("TaskGenie.Domain.Entities.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("project_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedByNavigationUserId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("Deadline")
                        .HasColumnType("date")
                        .HasColumnName("deadline");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<DateOnly?>("PredictedEndDate")
                        .HasColumnType("date")
                        .HasColumnName("predicted_end_date");

                    b.Property<int?>("Progress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("progress");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int")
                        .HasColumnName("team_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("ProjectId")
                        .HasName("PK__projects__BC799E1F9E7CEF3B");

                    b.HasIndex("CreatedByNavigationUserId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("TeamId");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("TaskGenie.Domain.Entities.ProjectEvaluation", b =>
                {
                    b.Property<int>("EvaluationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("evaluation_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EvaluationId"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comment");

                    b.Property<int?>("CommunicationScore")
                        .HasColumnType("int")
                        .HasColumnName("communication_score");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("EvaluatorId")
                        .HasColumnType("int")
                        .HasColumnName("evaluator_id");

                    b.Property<int?>("OverallScore")
                        .HasColumnType("int")
                        .HasColumnName("overall_score");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("project_id");

                    b.Property<int?>("QualityScore")
                        .HasColumnType("int")
                        .HasColumnName("quality_score");

                    b.Property<int?>("TimelinessScore")
                        .HasColumnType("int")
                        .HasColumnName("timeliness_score");

                    b.HasKey("EvaluationId")
                        .HasName("PK_project_evaluations");

                    b.HasIndex("EvaluatorId");

                    b.HasIndex("ProjectId");

                    b.ToTable("project_evaluations", (string)null);
                });

            modelBuilder.Entity("TaskGenie.Domain.Entities.Skill", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("skill_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillId"));

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("skill_name");

                    b.HasKey("SkillId")
                        .HasName("PK__skills__FBBA837902EF6DE9");

                    b.HasIndex(new[] { "SkillName" }, "UQ__skills__73C038AD12806053")
                        .IsUnique();

                    b.ToTable("skills", (string)null);
                });

            modelBuilder.Entity("TaskGenie.Domain.Entities.Task", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("task_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskId"));

                    b.Property<int?>("ActualTime")
                        .HasColumnType("int")
                        .HasColumnName("actual_time");

                    b.Property<int?>("AiEstimatedTime")
                        .HasColumnType("int")
                        .HasColumnName("ai_estimated_time");

                    b.Property<string>("AiSummary")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ai_summary");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("completed_at");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<DateOnly?>("Deadline")
                        .HasColumnType("date")
                        .HasColumnName("deadline");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int?>("Difficulty")
                        .HasColumnType("int")
                        .HasColumnName("difficulty");

                    b.Property<int?>("EstimatedTime")
                        .HasColumnType("int")
                        .HasColumnName("estimated_time");

                    b.Property<string>("Priority")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("priority");

                    b.Property<int?>("Progress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("progress");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("project_id");

                    b.Property<string>("RiskLevel")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("risk_level");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.Property<int?>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("TaskId")
                        .HasName("PK__tasks__0492148D776260FB");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ProjectId");

                    b.ToTable("tasks", null, t =>
                        {
                            t.HasTrigger("trg_task_update");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("TaskGenie.Domain.Entities.TaskAssignee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("TaskId")
                        .HasColumnType("int")
                        .HasColumnName("task_id");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__task_ass__3213E83F508CE41A");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "TaskId", "UserId" }, "UQ__task_ass__EF09F7FCB797C73F")
                        .IsUnique()
                        .HasFilter("[task_id] IS NOT NULL AND [user_id] IS NOT NULL");

                    b.ToTable("task_assignees", (string)null);
                });

            modelBuilder.Entity("TaskGenie.Domain.Entities.TaskComment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("comment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TaskId")
                        .HasColumnType("int")
                        .HasColumnName("task_id");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("CommentId")
                        .HasName("PK__task_com__E795768799D9D2A0");

                    b.HasIndex("TaskId");

                    b.HasIndex("UserId");

                    b.ToTable("task_comments", (string)null);
                });

            modelBuilder.Entity("TaskGenie.Domain.Entities.TaskDependency", b =>
                {
                    b.Property<int>("DependencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("dependency_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DependencyId"));

                    b.Property<int>("DependsOnTaskId")
                        .HasColumnType("int")
                        .HasColumnName("depends_on_task_id");

                    b.Property<int>("TaskId")
                        .HasColumnType("int")
                        .HasColumnName("task_id");

                    b.HasKey("DependencyId")
                        .HasName("PK_task_dependencies");

                    b.HasIndex("DependsOnTaskId");

                    b.HasIndex("TaskId");

                    b.ToTable("task_dependencies", (string)null);
                });

            modelBuilder.Entity("TaskGenie.Domain.Entities.TaskEmbedding", b =>
                {
                    b.Property<int>("TaskId")
                        .HasColumnType("int")
                        .HasColumnName("task_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Embedding")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("embedding");

                    b.HasKey("TaskId")
                        .HasName("PK__task_emb__0492148DABF2B4CD");

                    b.ToTable("task_embeddings", (string)null);
                });

            modelBuilder.Entity("TaskGenie.Domain.Entities.TaskLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("log_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<int?>("Progress")
                        .HasColumnType("int")
                        .HasColumnName("progress");

                    b.Property<string>("Risk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TaskId")
                        .HasColumnType("int")
                        .HasColumnName("task_id");

                    b.HasKey("LogId")
                        .HasName("PK__task_log__9E2397E0AC4592A4");

                    b.HasIndex("TaskId");

                    b.ToTable("task_logs", (string)null);
                });

            modelBuilder.Entity("TaskGenie.Domain.Entities.TaskRequiredSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("RequiredLevel")
                        .HasColumnType("int")
                        .HasColumnName("RequiredLevel");

                    b.Property<int?>("SkillId")
                        .HasColumnType("int")
                        .HasColumnName("SkillId");

                    b.Property<int?>("TaskId")
                        .HasColumnType("int")
                        .HasColumnName("TaskId");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskRequiredSkill", (string)null);
                });

            modelBuilder.Entity("TaskGenie.Domain.Entities.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("team_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamId"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.HasKey("TeamId")
                        .HasName("PK__teams__F82DEDBCF1BFE95F");

                    b.HasIndex("CreatedBy");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("TaskGenie.Domain.Entities.TeamMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Role")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("role");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int")
                        .HasColumnName("team_id");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__team_mem__3213E83FA2B300EE");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "TeamId", "UserId" }, "UQ__team_mem__13B60ECD7B0D1141")
                        .IsUnique()
                        .HasFilter("[team_id] IS NOT NULL AND [user_id] IS NOT NULL");

                    b.ToTable("team_members", (string)null);
                });

            modelBuilder.Entity("TaskGenie.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("avatar");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password");

                    b.Property<string>("Role")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("NORMAL_USER")
                        .HasColumnName("role");

                    b.Property<int?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId")
                        .HasName("PK__users__B9BE370FA9E917F7");

                    b.HasIndex(new[] { "Email" }, "UQ__users__AB6E616414D1BC50")
                        .IsUnique();

                    b.ToTable("users", null, t =>
                        {
                            t.HasTrigger("trg_user_status");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("TaskGenie.Domain.Entities.UserAvailability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AvailableHours")
                        .HasColumnType("int")
                        .HasColumnName("available_hours");

                    b.Property<int?>("DayOfWeek")
                        .HasColumnType("int")
                        .HasColumnName("day_of_week");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__user_ava__3213E83FAD6E302D");

                    b.HasIndex("UserId");

                    b.ToTable("user_availability", (string)null);
                });

            modelBuilder.Entity("TaskGenie.Domain.Entities.UserScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("project_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("reason");

                    b.Property<int?>("TaskId")
                        .HasColumnType("int")
                        .HasColumnName("task_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("type");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK_user_scores");

                    b.HasIndex("ProjectId");

                    b.HasIndex("TaskId");

                    b.HasIndex("UserId");

                    b.ToTable("user_scores", (string)null);
                });

            modelBuilder.Entity("TaskGenie.Domain.Entities.UserSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Level")
                        .HasColumnType("int")
                        .HasColumnName("level");

                    b.Property<int?>("SkillId")
                        .HasColumnType("int")
                        .HasColumnName("skill_id");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__user_ski__3213E83FF7FE70DE");

                    b.HasIndex("SkillId");

                    b.HasIndex(new[] { "UserId", "SkillId" }, "UQ__user_ski__36059F39B938ADFF")
                        .IsUnique()
                        .HasFilter("[user_id] IS NOT NULL AND [skill_id] IS NOT NULL");

                    b.ToTable("user_skills", (string)null);
                });

            modelBuilder.Entity("TaskGenie.Domain.Entities.AiAnalysis", b =>
                {
                    b.HasOne("TaskGenie.Domain.Entities.Task", "Task")
                        .WithMany("AiAnalyses")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_ai_analysis_tasks");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("TaskGenie.Domain.Entities.AiRecommendation", b =>
                {
                    b.HasOne("TaskGenie.Domain.Entities.User", "SuggestedUser")
                        .WithMany("AiRecommendations")
                        .HasForeignKey("SuggestedUserId")
                        .HasConstraintName("FK__ai_recomm__sugge__71D1E811");

                    b.HasOne("TaskGenie.Domain.Entities.Task", "Task")
                        .WithMany("AiRecommendations")
                        .HasForeignKey("TaskId")
                        .HasConstraintName("FK__ai_recomm__task___70DDC3D8");

                    b.Navigation("SuggestedUser");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("TaskGenie.Domain.Entities.Evaluation", b =>
                {
                    b.HasOne("TaskGenie.Domain.Entities.User", "Leader")
                        .WithMany("EvaluationLeaders")
                        .HasForeignKey("LeaderId")
                        .HasConstraintName("FK__evaluatio__leade__4CA06362");

                    b.HasOne("TaskGenie.Domain.Entities.User", "User")
                        .WithMany("EvaluationUsers")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__evaluatio__user___4BAC3F29");

                    b.Navigation("Leader");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaskGenie.Domain.Entities.Invitation", b =>
                {
                    b.HasOne("TaskGenie.Domain.Entities.Team", "Team")
                        .WithMany("Invitations")
                        .HasForeignKey("TeamId")
                        .HasConstraintName("FK__invitatio__team___5812160E");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("TaskGenie.Domain.Entities.Meeting", b =>
                {
                    b.HasOne("TaskGenie.Domain.Entities.User", "Organizer")
                        .WithMany()
                        .HasForeignKey("OrganizedBy")
                        .IsRequired()
                        .HasConstraintName("FK_meetings_users");

                    b.HasOne("TaskGenie.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_meetings_projects");

                    b.Navigation("Organizer");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("TaskGenie.Domain.Entities.MeetingAttendee", b =>
                {
                    b.HasOne("TaskGenie.Domain.Entities.Meeting", "Meeting")
                        .WithMany("Attendees")
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_meeting_attendees_meetings");

                    b.HasOne("TaskGenie.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_meeting_attendees_users");

                    b.Navigation("Meeting");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaskGenie.Domain.Entities.Notification", b =>
                {
                    b.HasOne("TaskGenie.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_notifications_users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaskGenie.Domain.Entities.Organization", b =>
                {
                    b.HasOne("TaskGenie.Domain.Entities.User", "Owner")
                        .WithMany("Organizations")
                        .HasForeignKey("OwnerId")
                        .HasConstraintName("FK_organizations_users");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("TaskGenie.Domain.Entities.Project", b =>
                {
                    b.HasOne("TaskGenie.Domain.Entities.User", "CreatedByNavigation")
                        .WithMany()
                        .HasForeignKey("CreatedByNavigationUserId");

                    b.HasOne("TaskGenie.Domain.Entities.Organization", "Organization")
                        .WithMany("Projects")
                        .HasForeignKey("OrganizationId")
                        .HasConstraintName("FK_projects_organizations");

                    b.HasOne("TaskGenie.Domain.Entities.Team", "Team")
                        .WithMany("Projects")
                        .HasForeignKey("TeamId")
                        .HasConstraintName("FK__projects__team_i__6E01572D");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Organization");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("TaskGenie.Domain.Entities.ProjectEvaluation", b =>
                {
                    b.HasOne("TaskGenie.Domain.Entities.User", "Evaluator")
                        .WithMany("ProjectEvaluations")
                        .HasForeignKey("EvaluatorId")
                        .IsRequired()
                        .HasConstraintName("FK_project_evaluations_users");

                    b.HasOne("TaskGenie.Domain.Entities.Project", "Project")
                        .WithMany("ProjectEvaluations")
                        .HasForeignKey("ProjectId")
                        .IsRequired()
                        .HasConstraintName("FK_project_evaluations_projects");

                    b.Navigation("Evaluator");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("TaskGenie.Domain.Entities.Task", b =>
                {
                    b.HasOne("TaskGenie.Domain.Entities.User", "CreatedByNavigation")
                        .WithMany("Tasks")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__tasks__created_b__5EBF139D");

                    b.HasOne("TaskGenie.Domain.Entities.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .HasConstraintName("FK__tasks__project_i__5DCAEF64");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("TaskGenie.Domain.Entities.TaskAssignee", b =>
                {
                    b.HasOne("TaskGenie.Domain.Entities.Task", "Task")
                        .WithMany("TaskAssignees")
                        .HasForeignKey("TaskId")
                        .HasConstraintName("FK__task_assi__task___693CA210");

                    b.HasOne("TaskGenie.Domain.Entities.User", "User")
                        .WithMany("TaskAssignees")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__task_assi__user___6A30C649");

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaskGenie.Domain.Entities.TaskComment", b =>
                {
                    b.HasOne("TaskGenie.Domain.Entities.Task", "Task")
                        .WithMany("TaskComments")
                        .HasForeignKey("TaskId")
                        .HasConstraintName("FK__task_comm__task___6D0D32F4");

                    b.HasOne("TaskGenie.Domain.Entities.User", "User")
                        .WithMany("TaskComments")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__task_comm__user___6E01572D");

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaskGenie.Domain.Entities.TaskDependency", b =>
                {
                    b.HasOne("TaskGenie.Domain.Entities.Task", "DependsOnTask")
                        .WithMany("DependentOnTasks")
                        .HasForeignKey("DependsOnTaskId")
                        .IsRequired()
                        .HasConstraintName("FK_task_dependencies_depends_on_task");

                    b.HasOne("TaskGenie.Domain.Entities.Task", "Task")
                        .WithMany("TaskDependencies")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_task_dependencies_task");

                    b.Navigation("DependsOnTask");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("TaskGenie.Domain.Entities.TaskEmbedding", b =>
                {
                    b.HasOne("TaskGenie.Domain.Entities.Task", "Task")
                        .WithOne("TaskEmbedding")
                        .HasForeignKey("TaskGenie.Domain.Entities.TaskEmbedding", "TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_task_embeddings_tasks");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("TaskGenie.Domain.Entities.TaskLog", b =>
                {
                    b.HasOne("TaskGenie.Domain.Entities.Task", "Task")
                        .WithMany("TaskLogs")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_task_logs_tasks");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("TaskGenie.Domain.Entities.TaskRequiredSkill", b =>
                {
                    b.HasOne("TaskGenie.Domain.Entities.Skill", "Skill")
                        .WithMany("TaskRequiredSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_TaskRequiredSkill_skills");

                    b.HasOne("TaskGenie.Domain.Entities.Task", "Task")
                        .WithMany("TaskRequiredSkills")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_TaskRequiredSkill_tasks");

                    b.Navigation("Skill");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("TaskGenie.Domain.Entities.Team", b =>
                {
                    b.HasOne("TaskGenie.Domain.Entities.User", "CreatedByNavigation")
                        .WithMany("Teams")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__teams__created_b__5070F446");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("TaskGenie.Domain.Entities.TeamMember", b =>
                {
                    b.HasOne("TaskGenie.Domain.Entities.Team", "Team")
                        .WithMany("TeamMembers")
                        .HasForeignKey("TeamId")
                        .HasConstraintName("FK__team_memb__team___5441852A");

                    b.HasOne("TaskGenie.Domain.Entities.User", "User")
                        .WithMany("TeamMembers")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__team_memb__user___5535A963");

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaskGenie.Domain.Entities.UserAvailability", b =>
                {
                    b.HasOne("TaskGenie.Domain.Entities.User", "User")
                        .WithMany("UserAvailabilities")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__user_avai__user___48CFD27E");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaskGenie.Domain.Entities.UserScore", b =>
                {
                    b.HasOne("TaskGenie.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .HasConstraintName("FK_user_scores_projects");

                    b.HasOne("TaskGenie.Domain.Entities.Task", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .HasConstraintName("FK_user_scores_tasks");

                    b.HasOne("TaskGenie.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_user_scores_users");

                    b.Navigation("Project");

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaskGenie.Domain.Entities.UserSkill", b =>
                {
                    b.HasOne("TaskGenie.Domain.Entities.Skill", "Skill")
                        .WithMany("UserSkills")
                        .HasForeignKey("SkillId")
                        .HasConstraintName("FK__user_skil__skill__44FF419A");

                    b.HasOne("TaskGenie.Domain.Entities.User", "User")
                        .WithMany("UserSkills")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__user_skil__user___440B1D61");

                    b.Navigation("Skill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaskGenie.Domain.Entities.Meeting", b =>
                {
                    b.Navigation("Attendees");
                });

            modelBuilder.Entity("TaskGenie.Domain.Entities.Organization", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("TaskGenie.Domain.Entities.Project", b =>
                {
                    b.Navigation("ProjectEvaluations");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("TaskGenie.Domain.Entities.Skill", b =>
                {
                    b.Navigation("TaskRequiredSkills");

                    b.Navigation("UserSkills");
                });

            modelBuilder.Entity("TaskGenie.Domain.Entities.Task", b =>
                {
                    b.Navigation("AiAnalyses");

                    b.Navigation("AiRecommendations");

                    b.Navigation("DependentOnTasks");

                    b.Navigation("TaskAssignees");

                    b.Navigation("TaskComments");

                    b.Navigation("TaskDependencies");

                    b.Navigation("TaskEmbedding");

                    b.Navigation("TaskLogs");

                    b.Navigation("TaskRequiredSkills");
                });

            modelBuilder.Entity("TaskGenie.Domain.Entities.Team", b =>
                {
                    b.Navigation("Invitations");

                    b.Navigation("Projects");

                    b.Navigation("TeamMembers");
                });

            modelBuilder.Entity("TaskGenie.Domain.Entities.User", b =>
                {
                    b.Navigation("AiRecommendations");

                    b.Navigation("EvaluationLeaders");

                    b.Navigation("EvaluationUsers");

                    b.Navigation("Organizations");

                    b.Navigation("ProjectEvaluations");

                    b.Navigation("TaskAssignees");

                    b.Navigation("TaskComments");

                    b.Navigation("Tasks");

                    b.Navigation("TeamMembers");

                    b.Navigation("Teams");

                    b.Navigation("UserAvailabilities");

                    b.Navigation("UserSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
